name:  Deploy

on:
  push:
    branches: [ main ]

jobs:
        
  deploy-staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    steps:
      - run: echo "Staging"
        
  deploy-production:
    name: Deploy to production
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Production"