name:  Deploy

on:
  push:
    branches: [ main ]

jobs:

        
  deploy-staging:
    name: Deploy to staging
    environment:
        name: staging
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is staging environment"

        
  deploy-production:
    name: Deploy to production
    environment:
        name: production
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Production"